---
version: 1
service:
  name: '{{ env "bamboo_deploy_environment" }}-{{ env "bamboo_shortPlanName" }}'
  shortname: ""
  owner: lab
deployment:
  strategy: blueGreen
health:
  delayseconds: 0
  path: "/"
  port: 8000
ports:
  - 8000
ingress:
  hosts:
    - host: 'api-tilehut-a.{{ env "bamboo_deploy_host" }}'
      public: false
    - host: 'api-tilehut-b.{{ env "bamboo_deploy_host" }}'
      public: false
    - host: 'api-tilehut-c.{{ env "bamboo_deploy_host" }}'
      public: false
    - host: 'api-tilehut-d.{{ env "bamboo_deploy_host" }}'
      public: false
autoscaling:
  min: 2
  max: 3
