---
version: 1
service:
  name: '{{ env "bamboo_deploy_environment" }}-{{ env "bamboo_shortPlanName" }}'
  shortname: ""
  owner: lab
deployment:
  strategy: blueGreen
health:
  delayseconds: 0
  path: "/"
  port: 8000
ports:
  - 8000
ingress:
  hosts:
    - host: 'tilehut-a.api.{{ env "bamboo_prod_host" }}'
      public: true
    - host: 'tilehut-b.api.{{ env "bamboo_prod_host" }}'
      public: true
    - host: 'tilehut-c.api.{{ env "bamboo_prod_host" }}'
      public: true
    - host: 'tilehut-d.api.{{ env "bamboo_prod_host" }}'
      public: true
autoscaling:
  min: 2
  max: 3
